version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - backend

  healthcare-poc-app:
    image: healthcare-poc
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.uri=mongodb://mongo:27017/trainingPoc
    networks:
      - backend
    depends_on:
      - mongodb

networks:
  backend:
    driver: bridge
